# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL_2'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  encoding: unicode
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL_2'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  encoding: unicode
  pool: 5
  timeout: 5000
